name: digi_store
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  loading_animation_widget: ^1.2.1
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^6.2.1
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  flutter_osm_plugin: ^0.70.4
  location: ^6.0.2
  image_cropper: ^8.0.1
  flutter_easyloading: ^3.0.5
  geocoding: ^2.0.0
  fluttertoast: ^8.2.8
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/png/logo.png"
  image_path_ios: "assets/png/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: dana
       fonts:
         - asset: assets/fonts/Dana-Bold.ttf
           weight: 700
         - asset: assets/fonts/Dana-Medium.ttf
           weight: 500
         - asset: assets/fonts/Dana-Regular.ttf
           weight: 400
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
